compute_environment: LOCAL_MACHINE
debug: false
distributed_type: NO
downcast_bf16: 'no'
enable_cpu_affinity: false
mixed_precision: fp8
fp8_config:
  backend: TE
  amax_compute_algo: max
  amax_history_len: 1024
  fp8_format: HYBRID
  interval: 1
  margin: 0
  override_linear_precision: [false, false, false]
  use_autocast_during_eval: false
gpu_ids: all
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
